/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as Under1000RouteImport } from './routes/under-1000'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as ApiPublicProductImageRouteImport } from './routes/api/public/product-image'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const Under1000Route = Under1000RouteImport.update({
  id: '/under-1000',
  path: '/under-1000',
  getParentRoute: () => rootRouteImport,
} as any)
const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicProductImageRoute = ApiPublicProductImageRouteImport.update({
  id: '/api/public/product-image',
  path: '/api/public/product-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/faq': typeof FaqRoute
  '/investment': typeof InvestmentRoute
  '/login': typeof LoginRoute
  '/prices': typeof PricesRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/try-on': typeof TryOnRoute
  '/under-1000': typeof Under1000Route
  '/why-us': typeof WhyUsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/shop/$id': typeof ShopIdRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/product-image': typeof ApiPublicProductImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/faq': typeof FaqRoute
  '/investment': typeof InvestmentRoute
  '/login': typeof LoginRoute
  '/prices': typeof PricesRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/try-on': typeof TryOnRoute
  '/under-1000': typeof Under1000Route
  '/why-us': typeof WhyUsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/shop/$id': typeof ShopIdRoute
  '/shop': typeof ShopIndexRoute
  '/api/public/product-image': typeof ApiPublicProductImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/faq': typeof FaqRoute
  '/investment': typeof InvestmentRoute
  '/login': typeof LoginRoute
  '/prices': typeof PricesRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/try-on': typeof TryOnRoute
  '/under-1000': typeof Under1000Route
  '/why-us': typeof WhyUsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/shop/$id': typeof ShopIdRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/product-image': typeof ApiPublicProductImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/faq'
    | '/investment'
    | '/login'
    | '/prices'
    | '/profile'
    | '/services'
    | '/signup'
    | '/try-on'
    | '/under-1000'
    | '/why-us'
    | '/wishlist'
    | '/admin/requests'
    | '/shop/$id'
    | '/shop/'
    | '/api/public/product-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/faq'
    | '/investment'
    | '/login'
    | '/prices'
    | '/profile'
    | '/services'
    | '/signup'
    | '/try-on'
    | '/under-1000'
    | '/why-us'
    | '/wishlist'
    | '/admin/requests'
    | '/shop/$id'
    | '/shop'
    | '/api/public/product-image'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/faq'
    | '/investment'
    | '/login'
    | '/prices'
    | '/profile'
    | '/services'
    | '/signup'
    | '/try-on'
    | '/under-1000'
    | '/why-us'
    | '/wishlist'
    | '/admin/requests'
    | '/shop/$id'
    | '/shop/'
    | '/api/public/product-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomRoute: typeof CustomRoute
  FaqRoute: typeof FaqRoute
  InvestmentRoute: typeof InvestmentRoute
  LoginRoute: typeof LoginRoute
  PricesRoute: typeof PricesRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  TryOnRoute: typeof TryOnRoute
  Under1000Route: typeof Under1000Route
  WhyUsRoute: typeof WhyUsRoute
  WishlistRoute: typeof WishlistRoute
  ShopIdRoute: typeof ShopIdRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiPublicProductImageRoute: typeof ApiPublicProductImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/under-1000': {
      id: '/under-1000'
      path: '/under-1000'
      fullPath: '/under-1000'
      preLoaderRoute: typeof Under1000RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/product-image': {
      id: '/api/public/product-image'
      path: '/api/public/product-image'
      fullPath: '/api/public/product-image'
      preLoaderRoute: typeof ApiPublicProductImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminRequestsRoute: typeof AdminRequestsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminRequestsRoute: AdminRequestsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomRoute: CustomRoute,
  FaqRoute: FaqRoute,
  InvestmentRoute: InvestmentRoute,
  LoginRoute: LoginRoute,
  PricesRoute: PricesRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  TryOnRoute: TryOnRoute,
  Under1000Route: Under1000Route,
  WhyUsRoute: WhyUsRoute,
  WishlistRoute: WishlistRoute,
  ShopIdRoute: ShopIdRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiPublicProductImageRoute: ApiPublicProductImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
